moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dual_arm_trajectory_controller

  dual_arm_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Joint1_L
      - Joint2_L
      - Joint3_L
      - Joint4_L
      - Joint5_L
      - Joint6_L
      - Joint7_L
      - Joint1_R
      - Joint2_R
      - Joint3_R
      - Joint4_R
      - Joint5_R
      - Joint6_R
      - Joint7_R
