controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ik_controller:
      type: marvin_system/IKController

ik_controller:
  ros__parameters:
    joints:
      - Joint1_L
      - Joint2_L
      - Joint3_L
      - Joint4_L
      - Joint5_L
      - Joint6_L
      - Joint7_L
      - Joint1_R
      - Joint2_R
      - Joint3_R
      - Joint4_R
      - Joint5_R
      - Joint6_R
      - Joint7_R
    kine_config_path: ""  # set by launch file via FindPackageShare
