controller_manager:
  ros__parameters:
    update_rate: 250 # in Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    rl_controller:
      type: ros2_control_wujihand/RLController

forward_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - finger0_joint0
      - finger0_joint1
      - finger0_joint2
      - finger0_joint3
      - finger1_joint0
      - finger1_joint1
      - finger1_joint2
      - finger1_joint3
      - finger2_joint0
      - finger2_joint1
      - finger2_joint2
      - finger2_joint3
      - finger3_joint0
      - finger3_joint1
      - finger3_joint2
      - finger3_joint3
      - finger4_joint0
      - finger4_joint1
      - finger4_joint2
      - finger4_joint3

rl_controller:
  ros__parameters:
    joints:
      - finger0_joint0
      - finger0_joint1
      - finger0_joint2
      - finger0_joint3
      - finger1_joint0
      - finger1_joint1
      - finger1_joint2
      - finger1_joint3
      - finger2_joint0
      - finger2_joint1
      - finger2_joint2
      - finger2_joint3
      - finger3_joint0
      - finger3_joint1
      - finger3_joint2
      - finger3_joint3
      - finger4_joint0
      - finger4_joint1
      - finger4_joint2
      - finger4_joint3
    command_interfaces:
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
    state_interfaces:
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - position
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity
      - velocity