recipe_id: cameras_wujihand_right_test
devices:
  - id: cam_high
    adapter: camera
    required: true
    depends_on: []
    ready_timeout_sec: 15.0
    startup_no_image_restart_timeout_sec: 12.0
    use_managed_launch: true
  - id: cam_left_wrist
    adapter: camera
    required: true
    depends_on: []
    ready_timeout_sec: 15.0
    use_managed_launch: true
  - id: cam_right_wrist
    adapter: camera
    required: true
    depends_on: []
    ready_timeout_sec: 15.0
    use_managed_launch: true
  - id: right_wujihand
    adapter: wujihand
    required: true
    depends_on:
      - cam_high
      - cam_left_wrist
      - cam_right_wrist
    use_managed_launch: true
    ready_timeout_sec: 30.0
    hand_side: right
    namespace: right_hand
    pipeline_namespace: right_hand
    joint_state_topic: /right_hand/joint_states
record_topics:
  - /cam_high/cam_high/color/image_raw
  - /cam_left_wrist/image_raw
  - /cam_right_wrist/image_raw
  - /right_hand/joint_states
  - /right_hand/forward_position_controller/commands
